{% set name = 'stsci.sphere' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: GPL
    summary: stsci.sphere

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}
    preserve_egg_dir: 'yes'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - astropy
    - matplotlib
    - setuptools
    - numpy
    - python x.x

    run:
    - astropy
    - matplotlib
    - numpy
    - python x.x

source:
    git_url: ssh://git@bitbucket.org/stsci_ssb/{{ name }}.git
test:
    imports:
    - stsci.sphere
