{% set name = 'drizzlepac' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/drizzlepac.git
    license: BSD
    summary: drizzlepac

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - astropy
    - fitsblender
    - nictools
    - scipy
    - stsci.convolve
    - stsci.image
    - stsci.imagemanip
    - stsci.imagestats
    - stsci.ndimage
    - stsci.skypac
    - stsci.sphere
    - stsci.stimage
    - stwcs
    - pyregion
    - setuptools
    - numpy
    - python x.x

    run:
    - astropy
    - fitsblender
    - nictools
    - scipy
    - stsci.convolve
    - stsci.image
    - stsci.imagemanip
    - stsci.imagestats
    - stsci.ndimage
    - stsci.skypac
    - stsci.sphere
    - stsci.stimage
    - stwcs
    - pyregion
    - setuptools
    - numpy
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - drizzlepac
