{% set name = 'astroimtools' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: astroimtools

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy
    - cython
    - matplotlib
    - setuptools
    - numpy
    - python x.x

    run:
    - astropy
    - cython
    - matplotlib
    - numpy
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    commands:
    - imarith --help
    - imstats --help
    imports:
    - astroimtools
