{% set name = 'd2to1' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/embray/{{ name }}
    license: BSD
    summary: d2to1

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - setuptools
    - python x.x

    run:
    - setuptools
    - python x.x

source:
    git_url: https://github.com/embray/{{ name }}.git
