{% set name = 'poppy' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/mperrin/{{ name }}
    license: BSD
    summary: poppy

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - nose
    - astropy
    - numpy
    - scipy
    - matplotlib
    - six [py27]
    - mock [py27]
    - enum34 [py27]
    - setuptools
    - python x.x

    run:
    - nose
    - astropy
    - numpy
    - scipy
    - matplotlib
    - six [py27]
    - mock [py27]
    - enum34 [py27]
    - setuptools
    - python x.x

source:
    git_url: https://github.com/mperrin/{{ name }}.git
