{% set name = 'stsci.skypac' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: stsci.skypac

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}
    preserve_egg_dir: 'yes'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - astropy
    - stsci.imagestats
    - stsci.sphere
    - stsci.tools
    - stwcs
    - setuptools
    - numpy
    - python x.x

    run:
    - astropy
    - stsci.imagestats
    - stsci.sphere
    - stsci.tools
    - stwcs
    - python x.x
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}

test:
    imports:
    - stsci.skypac
