{% set name = 'photutils' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/astropy/{{ name }}
    license: BSD
    summary: photutils

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - nose
    - astropy
    - cython
    - matplotlib
    - numpy
    - scikit-image
    - scipy
    - setuptools
    - python x.x

    run:
    - astropy
    - cython
    - matplotlib
    - numpy
    - scikit-image
    - scipy
    - setuptools
    - python x.x

source:
    git_url: https://github.com/astropy/{{ name }}.git

test:
    imports:
    - photutils
