{% set name = 'jwst_gtvt' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Calculates the allowed position angle for a given Right Ascension and
        Declination for each instrument.

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy
    - matplotlib
    - numpy
    - setuptools
    - python x.x

    run:
    - astropy
    - matplotlib
    - numpy
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git
