{% set name = 'costools' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: http://www.stsci.edu/institute/software_hardware
    license: BSD
    summary: costools

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - astropy
    - calcos
    - stsci.tools
    - setuptools
    - numpy
    - python x.x

    run:
    - d2to1
    - astropy
    - calcos
    - stsci.tools
    - setuptools
    - numpy
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    commands:
    - timefilter --help
    imports:
    - costools
