{% set name = 'pyraf' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: pyraf

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - astropy
    - ipython
    - matplotlib
    - pyobjc-core [osx]
    - pyobjc-framework-cocoa [osx]
    - pyobjc-framework-quartz [osx]
    - stsci.distutils
    - stsci.tools
    - setuptools
    - numpy
    - python x.x

    run:
    - d2to1
    - astropy
    - ipython
    - matplotlib
    - pyobjc-core [osx]
    - pyobjc-framework-cocoa [osx]
    - pyobjc-framework-quartz [osx]
    - stsci.tools
    - numpy
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    commands:
    - pyraf --help
