{% set name = 'specviz' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
  home: https://github.com/spacetelescope/specviz
  license: BSD

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: {{ number }}
  string: {{ GIT_BUILD_STR }}_{{ number }}

source:
  git_tag: {{ tag }}
  git_url: https://github.com/spacetelescope/specviz.git

requirements:
  build:
    - astropy
    - cython
    - specutils
    - pyyaml
    - pyqtgraph >=0.9.11
    - pyqt
    - scipy
    - yaml
    - setuptools
    - numpy
    - python x.x

  run:
    - astropy
    - cython
    - specutils
    - pyyaml
    - pyqtgraph >=0.9.11
    - pyqt
    - scipy
    - yaml
    - numpy
    - python x.x

test:
  requires:
    - astropy
    - specutils
  imports:
    - specviz

