{% set name = 'glue-vispy-viewers' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}
{% set baseurl = 'https://github.com/glue-viz' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: {{ baseurl }}/{{ name }}

build:
  number: {{ number }}
  string: {{ GIT_BUILD_STR }}_{{ number }}
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pyopengl
    - glue-core >=0.10

  run:
    - python
    - numpy
    - pyopengl
    - glue-core >=0.10
    - matplotlib
    - qtpy
    - pyqt

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: {{ baseurl }}/{{ name }}
  license: BSD 3-Clause
  summary: 3D viewers for Glue
