# NOTE: this is a meta-package that includes the core glue code as well as stable
# plugins. This is the main conda package we want in the Navigator, so we add the
# app: entry here and not in the glue-core package.

{% set name = 'glueviz' %}
{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0")
    +".dev"
    +environ.get("GIT_DESCRIBE_NUMBER", "0") %}
{% set number = '0' %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: {{ number }}

requirements:
  build:
    - python
    - setuptools
    - glue-vispy-viewers >=0.7.2

  run:
    - glue-vispy-viewers >=0.7.2
    - glue-ginga

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  summary: Multi-dimensional linked data exploration
