{% set name = 'jwst_lib' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: ssh://git@bitbucket.org/stsci_ssb/jwst.git
    license: BSD
    summary: jwst_lib

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}
    preserve_egg_dir: 'True'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - asdf
    - astropy
    - crds
    - gwcs
    - jsonschema
    - nose
    - six
    - stsci.distutils
    - numpy
    - setuptools
    - python x.x

    run:
    - asdf
    - astropy
    - crds
    - gwcs
    - nose
    - jsonschema
    - six
    - numpy
    - python x.x

source:
    git_url: ssh://git@bitbucket.org/stsci_ssb/jwst.git

test:
    imports:
    - jwst_lib
