{% set name = 'asdf-standard' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: asdf-standard

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - sphinx
    - jsonschema
    - pyyaml
    - mistune
    - six [py27|py3k]
    - setuptools
    - python x.x

    run:
    - nose
    - astropy
    - setuptools
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git
