{% set name = 'pandokia' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: http://ssb.stsci.edu/testing/{{ name }}
    license: BSD
    summary: pandokia

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - nose
    - pytest
    - shunit2
    - setuptools
    - python x.x

    run:
    - nose
    - shunit2
    - pytest
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    commands:
    - pdk --help
    imports:
    - pandokia
    - pandokia.runners
    - pandokia.helpers
