{% set name = 'jwst' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/stsci-jwst/{{ name }}
    license: BSD
    summary: JWST Pipeline code

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}
    preserve_egg_dir: 'True'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy
    - numpy >=1.7*
    - setuptools
    - python x.x

    run:
    - asdf
    - astropy
    - crds
    - dask
    - drizzle
    - drizzlepac
    - gwcs
    - jsonschema
    - jplephem
    - matplotlib
    - nose
    - photutils
    - pymssql
    - scipy
    - six
    - verhawk
    - numpy >=1.7*
    - python x.x

source:
    git_url: https://github.com/stsci-jwst/{{ name }}.git

test:
    imports:
    - jwst
    - jwst.steps
    # no timeconversion: JPL network is too unstable to obtain *.bsp files.
