{% set name = 'aprio' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: http://bitbucket.org/jhunkeler/{{ name }}
    license: GPL
    summary: aprio is an automatic renice daemon.

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - argparse >=1.1 [py26]
    - docutils
    - psutil
    - python-daemon
    - setuptools
    - python x.x

    run:
    - docutils
    - psutil
    - python-daemon
    - python x.x

source:
    git_url: https://bitbucket.org/jhunkeler/{{ name }}.git
