{% set name = 'stsci.distutils' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: stsci.distutils

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - setuptools
    - numpy
    - python x.x

    run:
    - nose
    - numpy
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stsci.distutils
