{% set name = 'asdf' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: asdf

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy
    - pyyaml
    - jsonschema
    - pytest
    - six
    - setuptools
    - numpy
    - python x.x

    run:
    - astropy
    - pyyaml
    - jsonschema
    - pytest
    - six
    - setuptools
    - numpy
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    commands:
    - asdftool --help
    imports:
    - asdf
