{% set name = 'imgeom' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Tools for dealing with mapping coordinates, measurements, and models between overlapping images

package:
    name: {{ name }}
    version: {{ version }}

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

requirements:
    build:
    - astropy
    - drizzle
    - gwcs
    - setuptools
    - python x.x

    run:
    - astropy
    - drizzle
    - gwcs
    - numpy
    - python x.x

test:
    imports:
    - imgeom
    - imgeom.drizmask
    - imgeom.fitting
    - imgeom.reproject
