{% set name = 'specutils' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/astropy/specutils
    license: BSD
    summary: One-dimensional spectral operations

package:
    name: {{ name }}
    version: {{ version }}

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

source:
    git_url: https://github.com/astropy/{{ name }}.git

requirements:
    build:
    - astropy
    - cython
    - scipy
    - setuptools
    - numpy
    - python x.x

    run:
    - astropy
    - scipy
    - numpy
    - python x.x

test:
    imports:
    - specutils
    - specutils.io
    - specutils.models
    - specutils.utils
    - specutils.wcs

