{% set name = 'stsci.sphinxext' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: stsci.sphinxext

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}
    preserve_egg_dir: 'yes'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - numpydoc
    - setuptools
    - python x.x

    run:
    - numpydoc
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stsci.sphinxext
