{% set name = 'ext_shmht' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/stsci-ssb/{{ name }}
    license: BSD
    summary: ext_shmht

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - setuptools
    - python x.x

    run:
    - six
    - python x.x

source:
    git_url: https://github.com/stsci-ssb/{{ name }}.git

test:
    imports:
    - ext_shmht
