{% set name = 'pyds9' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/ericmandel/{{ name }}
    license: GPL
    summary: Python connection to SAOimage DS9 via XPA

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy
    - xpa
    - ds9
    - six
    - setuptools
    - numpy
    - python x.x

    run:
    - astropy
    - xpa
    - ds9
    - six
    - numpy
    - python x.x

source:
    git_url: https://github.com/ericmandel/{{ name }}.git

test:
    imports:
    #- pyds9
    #  ^ Disabled, because it leaves behind the xpans daemon
