{% set name = 'purge_path' %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set number = '0' %}

about:
    home: https://github.com/jhunkeler/{{ name }}
    license: BSD
    summary: purge_path a small PATH manipulator

build:
    number: {{ number }}
    string: {{ GIT_BUILD_STR }}_{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - python x.x
    - setuptools

    run:
    - python x.x

source:
    git_url: https://github.com/jhunkeler/{{ name }}.git
